#pragma once

#define IMG_BACK_WIDTH 600
#define IMG_BACK_HEIGHT 800
//玩家飞机的大小
#define IMG_PLAYER_WIDTH  60
#define IMG_PLAYER_HEIGHT 60
//炮弹的大小
#define IMG_GUNNER_WIDTH  6
#define IMG_GUNNER_HEIGHT 20

#define BACK_MOVE_TIMERID 1
#define BACK_MOVE_INTERVAL 50
#define BACK_MOVE_STEP 2

#define PLAYER_MOVE_TIMERID 2
#define PLAYER_MOVE_INTERVAL 10
#define PLAYER_MOVE_STEP 3

#define GUNNER_SEND_TIMERID 3
#define GUNNER_SEND_INTERVAL 500
#define GUNNER_MOVE_TIMERID 4
#define GUNNER_MOVE_INTERVAL 50
#define GUNNER_MOVE_STEP -5

#define FOEBIG_CREATE_TIMERID 5
#define FOEBIG_CREATE_INTERVAL 12000

#define FOEMID_CREATE_TIMERID 6
#define FOEMID_CREATE_INTERVAL 9000

#define FOESMA_CREATE_TIMERID 7
#define FOESMA_CREATE_INTERVAL 6000

#define FOE_MOVE_TIMERID 8
#define FOE_MOVE_INTERVAL 50

#define CHECK_HIT_TIMERID 9
#define CHECK_HIT_INTERVAL 5

#define CHANGE_PIC_TIMERID 10
#define CHANGE_PIC_INTERVAL 300


//三种敌人飞机的大小
#define IMG_FOE_BIG_WIDTH  150
#define IMG_FOE_BIG_HEIGHT 100

#define IMG_FOE_MID_WIDTH  80
#define IMG_FOE_MID_HEIGHT 60

#define IMG_FOE_SMA_WIDTH  60
#define IMG_FOE_SMA_HEIGHT 40



#define GUNNER_HURT 1
#define FOEBIG_BLOOD 5
#define FOEMID_BLOOD 3
#define FOESMA_BLOOD 1

#define FOEBIG_MOVE_STEP 4
#define FOEMID_MOVE_STEP 6
#define FOESMA_MOVE_STEP 8

